name: hookup4u
version: 1.0.14+58
#version: 1.0.12+57
description: A new Flutter application.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  google_mobile_ads: ^2.3.0
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.4.0
  swipe_stack: ^1.0.0
  flutter_swiper_null_safety: ^1.0.2
  intl: ^0.17.0
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  location: ^4.3.0
  # flutter_geocoder: ^0.2.2-nullsafety
  geocoding: ^2.0.5
  image_picker: ^0.8.4+7
  image_cropper: ^1.2.1
  firebase_storage: ^11.0.10
  path_provider: any
  cached_network_image: ^3.2.0
  share: ^2.0.4
  firebase_messaging: ^14.2.1
  webview_flutter: ^3.0.0
  in_app_purchase: ^2.0.1
  rflutter_alert: ^2.0.4
  permission_handler: ^8.3.0
  flutter_ringtone_player: ^3.1.1
  shimmer: ^2.0.0
  the_apple_sign_in: ^1.1.1
  sign_in_with_apple: ^4.3.0
  url_launcher: ^6.0.18
  flutter_mapbox_autocomplete: ^2.0.0
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.4
  firebase_core: ^2.4.1
  flutter_launcher_icons: ^0.9.2
  dropdown_search: ^2.0.1
  auto_size_text: ^3.0.0
  flutter_local_notifications: ^9.4.0
  art_sweetalert: ^0.0.5
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.2.0
  percent_indicator: ^4.0.1
  flutter_slidable: ^1.3.2
  google_sign_in: ^5.3.3
  flutter_spinkit: ^5.1.0
  get: 4.6.5
  translator: ^0.1.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  change_app_package_name: ^1.0.0
  flutter_app_name: ^0.1.1
  flutter_test: 
    sdk: flutter

flutter_app_name: 
  name: Unjabbed

flutter_icons: 
  android: launcher_icon
  image_path: asset/images/logo2.png
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - asset/auth/
    - asset/
    - asset/translation/
    - asset/images/
  fonts: 
    - family: Arial
      fonts: 
        - asset: asset/fonts/arial/ArialTh.ttf
  uses-material-design: true

